services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000" # Expose FastAPI
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000" # Expose Next.js
    env_file: ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network
    profiles:
      - dev

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose Nginx
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - app-network
    profiles:
      - prod

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
