services:
  backend_prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/backend
    networks:
      - app-network
    profiles:
      - prod

  backend_dev: # creating a separate backend service for dev profile for db service
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    networks:
      - app-network
    profiles:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    env_file: ./frontend/.env
    depends_on:
      - backend_dev
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network
    profiles:
      - dev

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: ./backend/.env # required attribute (if not "environment" attribute)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
