services:
  fastapi:
    build: .
    container_name: fastapi-app
    env_file: ".env"
    ports:
      - "8000:8000"
    volumes:
      - .:/backend # map host dir to container dir
    depends_on:
      - postgres
    command: fastapi run main.py --port 8000

  postgres:
    image: postgres:13
    container_name: postgres-db
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
