import NextAuth from "next-auth/next";
import Credentials from "next-auth/providers/credentials";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

const handler = NextAuth({
  secret: process.env.AUTH_SECRET,
  providers: [
    Credentials({
      // The name to display on the sign in form (e.g. "Sign in with...")
      name: "Credentials",
      // `credentials` is used to generate a form on the sign in page.
      // You can specify which fields should be submitted, by adding keys to the `credentials` object.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
      credentials: {
        username: { label: "Username", type: "text", placeholder: "username" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials, req) {
        if (credentials == undefined) return null;

        // Add logic here to look up the user from the credentials supplied
        const res = await fetch("http://localhost:8000/auth/token", {
          method: "POST",
          headers: { "Content-Type": "application/x-www-form-urlencoded" },
          body: new URLSearchParams({
            username: credentials.username,
            password: credentials.password,
          }),
        });
        const response = await res.json();
        if (res.ok) {
          // If status code 200 returned
          console.log("Response OK:", response);
          return { ...response };
        } else {
          // If you return null then an error will be displayed advising the user to check their details.
          console.log("Response NOT OK:", response);
          return null;
          // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
        }
      },
    }),
  ],
  callbacks: {
    async jwt({ token }) {
      // token combined with token info generated by next-auth and data from response returned by `authorize`
      return { ...token };
    },
    async session({ session, token, user }) {
      // token combined with token info generated by next-auth and data from response returned by `authorize`
      session.user = token;
      return session;
    },
  },
});

export { handler as GET, handler as POST };
